# Generated by Django 4.1.7 on 2023-02-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_short', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('coordinates_lng', models.CharField(max_length=200)),
                ('coordinates_lat', models.CharField(max_length=200)),
                ('place_id', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
