# Generated by Django 4.1.7 on 2023-03-06 16:14

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_short', models.TextField()),
                ('description_long', tinymce.models.HTMLField()),
                ('lng', models.FloatField(max_length=200)),
                ('lat', models.FloatField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('image_number', models.IntegerField()),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='places.place')),
            ],
            options={
                'ordering': ['image_number'],
            },
        ),
    ]
