# Generated by Django 4.1.7 on 2023-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description_short',
            field=models.TextField(),
        ),
    ]
