# Generated by Django 4.1.7 on 2023-03-03 14:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_options_alter_image_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
