# Generated by Django 4.1.7 on 2023-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_places_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.IntegerField(db_index=True, default=1, null=True, unique=True),
        ),
    ]
