# Generated by Django 4.1.7 on 2023-03-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_image_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='text',
            new_name='description_long',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='coordinates_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='coordinates_lng',
            new_name='lng',
        ),
    ]
