# Generated by Django 4.1.7 on 2023-03-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_places_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='place_id',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.IntegerField(blank=True, db_index=True, default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='lat',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='places',
            name='lng',
            field=models.FloatField(max_length=200),
        ),
    ]
