# Generated by Django 4.1.7 on 2023-03-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_image_places'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
